### ISSUE TITLE
16 bit test failure

### ISSUE THREAD

**Issue by devanshkv** [AA-ALERT/psrdada-python#5]
I have been tying to dump some data into the dada buffers using this code and write it out as `.dada` files using `dada_dbdisk`. It works fine when I dump 8 bit data with `np.uint8` but fails with `np.uint16`.

I then tried fiddling around with the tests and they work in the present state. However if I change https://github.com/TRASAL/psrdada-python/blob/977cb6c6501998082d6f836f8103c0a8fcf35485/tests/test_data.py#L19 to
``` python
TEST_DATA = np.random.randint(0,(2**16 -1), TEST_SIZE)
```
it breaks! I am probably missing something or misunderstanding some key concept. Any help would would be greatly appreciated!

**Comment by jiskattema** [comment]
The dada ringbuffer is in unsigned bytes, so you can't directly store 16 bit integers like you suggest.
For reading and writing different types from the ringbuffer you need to specify the type.

I think something like:
```
data = np.asarray(page, dtype=np.dtype('u'))
```
See the numpy [documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

**Comment by jiskattema** [comment]
re-reading your issue, i see that you probably used the correct types (np.uint etc).

Another issue that will break the test the ```TEST_SIZE```, going over the code it is used as a number of elements:
```
TEST_DATA = np.random.randint(0, 255, TEST_SIZE)
```

but also as a number of bytes:
```
os.system("dada_db -d 2>/dev/null;dada_db -b %i -k dada" % (TEST_SIZE))
```
ie. the size in bytes of the ringbuffer is set to ```TEST_SIZE```; but should be ```TEST_SIZE * 2``` for 16 bit integers.

**Comment by devanshkv** [comment]
Thanks for getting back. Here is what I have tried:

1. `np.random.randint` creates an `int64` dtype array, which means the TEST_DATA has the size of 4194304 bytes. This can be confirmed by `TEST_DATA.itemsize` which gives 8 bytes.

As you mentioned above, the following https://github.com/TRASAL/psrdada-python/blob/977cb6c6501998082d6f836f8103c0a8fcf35485/tests/test_data.py#L31
then should be modified to
```python
os.system("dada_db -d 2>/dev/null;dada_db -b %i -k dada" % (TEST_SIZE* TEST_DATA.itemsize)) 
```
and https://github.com/TRASAL/psrdada-python/blob/977cb6c6501998082d6f836f8103c0a8fcf35485/tests/test_data.py#L56
to
``` python
data = np.asarray(page, dtype = TEST_DATA.dtype) 
```
but doing that makes the tests fail because now the array sizes are different
```bash
test_writing_data (test_data.TestReadWriteData)
Data reading and writing test. ... sh: line 1: 14674 Segmentation fault      (core dumped) dada_db -d 2> /dev/null
Created DADA data block with nbufs=4 bufsz=4194304 nread=1
Created DADA header block with nhdrs = 8, hdrsz = 4096 bytes, nread=1
ERROR
test_writing_data (test_data.TestReadWriteDataIterator)
Data reading and writing test. ... sh: line 1: 14683 Segmentation fault      (core dumped) dada_db -d 2> /dev/null
Created DADA data block with nbufs=4 bufsz=524288 nread=1
Created DADA header block with nhdrs = 8, hdrsz = 4096 bytes, nread=1
ok

======================================================================
ERROR: test_writing_data (test_data.TestReadWriteData)
Data reading and writing test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/hyrule/data/users/dagarwal/4bit_testing/test_data.py", line 61, in test_writing_data
    data[...] = TEST_DATA[...]
ValueError: could not broadcast input array from shape (524288,) into shape (4194304,)

----------------------------------------------------------------------
Ran 2 tests in 0.446s

FAILED (errors=1)
```
Now the tests only pass when I set
```python
TEST_DATA = np.random.randint(low=0, high = 255, size = TEST_SIZE, dtype = np.uint8)
```
2. With the original test file, the tests pass when the low and high values are between 0 to 255, I tried the following cases
```python
TEST_DATA = np.random.randint(low=0, high = 255, size = TEST_SIZE, dtype = np.uint8)
TEST_DATA = np.random.randint(low=0, high = 255, size = TEST_SIZE, dtype = np.uint16)
TEST_DATA = np.random.randint(low=0, high = 255, size = TEST_SIZE, dtype = np.uint32)
TEST_DATA = np.random.randint(low=0, high = 255, size = TEST_SIZE, dtype = np.uint64)
```
and all of the cases pass, this is weird because in all 4 cases the TEST_DATA array has a different size because of different dtypes. The tests only fail when high > 256 (for dtypes above uint8).

**Comment by jiskattema** [comment]
The problem seems to be converting the ring buffer page to a python array of doubles, both the original as my first suggestion don't do it right.
This line:
```
data[...] = TEST_DATA[...]
```
indeed fails because the array sizes are different: each element is converted individually from char to double, instead of taking 8 chars and making a single double.

Have a look at [this stackoverflow](https://stackoverflow.com/questions/20530678/how-can-i-convert-a-byte-array-to-a-double-in-python) discussion.
I think the original ringbuffer ```page```,  or the numpy array ```data = np.asarray(page)``` needs to be packed and unpacked using the ```struct``` module.

**Comment by devanshkv** [comment]
Thanks for poting this out. This is what works for me:
Create a dict to map dtypes and then `cast` the page memoryview object. More details are [here](https://docs.python.org/3/library/struct.html#format-characters).
```python
cast_dict = {"uint8": "B", "uint16": "H", "int16": "h", "float32": "f"}
page = writer.getNextPage().cast(cast_dict[str(data_input.dtype)])
data = np.asarray(page, dtype=data_input.dtype)
data[...] = data_input[...]
```

**Comment by jiskattema** [comment]
If you have a minimal example (like the test cases), feel free to make a pull request so I can add it as a test case.
