### ISSUE TITLE
Wrong parameter to initialize writer/reader class in example. It should be 0xdada instead of 0xdbda

### ISSUE THREAD

**Issue by yyihuan** [AA-ALERT/psrdada-python#6]
The default buffer created using dada_db has an identifier of 0xdada, the example in the readme file is correct, but the example files are all wrong.
[Environment]
psrdada_python  == 0.1.0
psrdada == 1.0.0
Ubuntu20.04

**Comment by isazi** [comment]
Hi @yyihuan thanks for reporting this. Would you like to send a pull request with the fix for this typo?

**Comment by isazi** [comment]
Fixed the examples.
